name: CD pipeline

on:
  workflow_run:
    workflows: [ "Docker Image CI" ]
    types:
      - completed
  #pull_request:
    #branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name : Pull Image from Docker Hub
    - run : docker pull nihaparasa/hydroapp:latest
    - name : Delete the old docker container
    - run : docker rm -f hydroapp-container || true
    - name : Run docker container with latest image
    - run : sudo docker run -td -p 8080:8080 --name hydroapp-container nihaparasa/hydroapp
    
      
